<!DOCTYPE HTML>
<html lang="en">
<head>
<!-- Generated by javadoc (17) -->
<title>Source code</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="source: package: com.googlecode.catchexception, class: CatchException">
<meta name="generator" content="javadoc/SourceToHTMLConverter">
<link rel="stylesheet" type="text/css" href="../../../../stylesheet.css" title="Style">
</head>
<body class="source-page">
<main role="main">
<div class="source-container">
<pre><span class="source-line-no">001</span><span id="line-1">/**</span>
<span class="source-line-no">002</span><span id="line-2"> * Copyright (C) 2011 rwoo@gmx.de</span>
<span class="source-line-no">003</span><span id="line-3"> *</span>
<span class="source-line-no">004</span><span id="line-4"> * Licensed under the Apache License, Version 2.0 (the "License");</span>
<span class="source-line-no">005</span><span id="line-5"> * you may not use this file except in compliance with the License.</span>
<span class="source-line-no">006</span><span id="line-6"> * You may obtain a copy of the License at</span>
<span class="source-line-no">007</span><span id="line-7"> *</span>
<span class="source-line-no">008</span><span id="line-8"> *         http://www.apache.org/licenses/LICENSE-2.0</span>
<span class="source-line-no">009</span><span id="line-9"> *</span>
<span class="source-line-no">010</span><span id="line-10"> * Unless required by applicable law or agreed to in writing, software</span>
<span class="source-line-no">011</span><span id="line-11"> * distributed under the License is distributed on an "AS IS" BASIS,</span>
<span class="source-line-no">012</span><span id="line-12"> * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.</span>
<span class="source-line-no">013</span><span id="line-13"> * See the License for the specific language governing permissions and</span>
<span class="source-line-no">014</span><span id="line-14"> * limitations under the License.</span>
<span class="source-line-no">015</span><span id="line-15"> */</span>
<span class="source-line-no">016</span><span id="line-16">package com.googlecode.catchexception;</span>
<span class="source-line-no">017</span><span id="line-17"></span>
<span class="source-line-no">018</span><span id="line-18">import com.googlecode.catchexception.apis.BDDCatchException;</span>
<span class="source-line-no">019</span><span id="line-19">import com.googlecode.catchexception.apis.CatchExceptionHamcrestMatchers;</span>
<span class="source-line-no">020</span><span id="line-20"></span>
<span class="source-line-no">021</span><span id="line-21">/**</span>
<span class="source-line-no">022</span><span id="line-22"> * The methods of this class catch and verify exceptions in &lt;em&gt;a single line of</span>
<span class="source-line-no">023</span><span id="line-23"> * code&lt;/em&gt; and make them available for further analysis.</span>
<span class="source-line-no">024</span><span id="line-24"> *</span>
<span class="source-line-no">025</span><span id="line-25"> * This Javadoc content is also available on the &lt;a</span>
<span class="source-line-no">026</span><span id="line-26"> * href="http://code.google.com/p/catch-exception/" &gt;catch-exception&lt;/a&gt; web</span>
<span class="source-line-no">027</span><span id="line-27"> * page.</span>
<span class="source-line-no">028</span><span id="line-28"> *</span>
<span class="source-line-no">029</span><span id="line-29"> * &lt;strong&gt;Documentation&lt;/strong&gt;</span>
<span class="source-line-no">030</span><span id="line-30"> *</span>
<span class="source-line-no">031</span><span id="line-31"> * &lt;b&gt; &lt;a href="#1"&gt;1. How to use catch-exception?&lt;/a&gt;</span>
<span class="source-line-no">032</span><span id="line-32"></span>
<span class="source-line-no">033</span><span id="line-33"> * &lt;a href="#2"&gt;2. What is this stuff actually good for?&lt;/a&gt;</span>
<span class="source-line-no">034</span><span id="line-34"></span>
<span class="source-line-no">035</span><span id="line-35"> * &lt;a href="#3"&gt;3. How does it work internally?&lt;/a&gt;</span>
<span class="source-line-no">036</span><span id="line-36"></span>
<span class="source-line-no">037</span><span id="line-37"> * &lt;a href="#4"&gt;4. When is the caught exception reset?&lt;/a&gt;</span>
<span class="source-line-no">038</span><span id="line-38"></span>
<span class="source-line-no">039</span><span id="line-39"> * &lt;a href="#5"&gt;5. My code throws a ClassCastException. Why?&lt;/a&gt;</span>
<span class="source-line-no">040</span><span id="line-40"></span>
<span class="source-line-no">041</span><span id="line-41"> * &lt;a href="#6"&gt;6. The exception is not caught. Why?&lt;/a&gt;</span>
<span class="source-line-no">042</span><span id="line-42"></span>
<span class="source-line-no">043</span><span id="line-43"> * &lt;a href="#7"&gt;7. Do I have to care about memory leaks?&lt;/a&gt;</span>
<span class="source-line-no">044</span><span id="line-44"></span>
<span class="source-line-no">045</span><span id="line-45"> * &lt;a href="#8"&gt;8. The caught exception is not available in another thread.</span>
<span class="source-line-no">046</span><span id="line-46"> * Why?&lt;/a&gt;</span>
<span class="source-line-no">047</span><span id="line-47"></span>
<span class="source-line-no">048</span><span id="line-48"> * &lt;a href="#9"&gt;9. How do I catch an exception thrown by a static method?&lt;/a&gt;</span>
<span class="source-line-no">049</span><span id="line-49"></span>
<span class="source-line-no">050</span><span id="line-50"> * &lt;a href="#11"&gt;11. Can I catch errors instead of exceptions?&lt;/a&gt;</span>
<span class="source-line-no">051</span><span id="line-51"></span>
<span class="source-line-no">052</span><span id="line-52"> *</span>
<span class="source-line-no">053</span><span id="line-53"> *</span>
<span class="source-line-no">054</span><span id="line-54"> *</span>
<span class="source-line-no">055</span><span id="line-55"> * &lt;/b&gt;</span>
<span class="source-line-no">056</span><span id="line-56"> *</span>
<span class="source-line-no">057</span><span id="line-57"> * &lt;strong&gt;1. How to use catch-exception?&lt;/strong&gt;</span>
<span class="source-line-no">058</span><span id="line-58"> *</span>
<span class="source-line-no">059</span><span id="line-59"> * The most basic usage is:</span>
<span class="source-line-no">060</span><span id="line-60"> * &lt;code&gt;import static com.googlecode.catchexception.CatchException.*;</span>
<span class="source-line-no">061</span><span id="line-61"> *</span>
<span class="source-line-no">062</span><span id="line-62"> * // call customerService.prepareBilling(Prize.Zero)</span>
<span class="source-line-no">063</span><span id="line-63"> * // and catch the exception if any is thrown</span>
<span class="source-line-no">064</span><span id="line-64"> * catchException(customerService).prepareBilling(Prize.Zero);</span>
<span class="source-line-no">065</span><span id="line-65"> *</span>
<span class="source-line-no">066</span><span id="line-66"> * // assert that an IllegalArgumentException was thrown</span>
<span class="source-line-no">067</span><span id="line-67"> * assert caughtException() instanceof IllegalArgumentException;&lt;/code&gt;</span>
<span class="source-line-no">068</span><span id="line-68"> *</span>
<span class="source-line-no">069</span><span id="line-69"> * You can combine the two lines of code in a single one if you like:</span>
<span class="source-line-no">070</span><span id="line-70"> * &lt;code&gt;// call customerService.prepareBilling(Prize.Zero)</span>
<span class="source-line-no">071</span><span id="line-71"> * // and throw an ExceptionNotThrownAssertionError if</span>
<span class="source-line-no">072</span><span id="line-72"> * // the expected exception is not thrown</span>
<span class="source-line-no">073</span><span id="line-73"> * verifyException(customerService, IllegalArgumentException.class).prepareBilling(Prize.Zero);&lt;/code&gt;</span>
<span class="source-line-no">074</span><span id="line-74"> * There is a minor difference between both variants. In the first variant you</span>
<span class="source-line-no">075</span><span id="line-75"> * must start the JVM with option &lt;code&gt;-ea&lt;/code&gt; to enable the assertion. The</span>
<span class="source-line-no">076</span><span id="line-76"> * second variant does not use JDK assertions and ,therefore, always verifies</span>
<span class="source-line-no">077</span><span id="line-77"> * the caught exception.</span>
<span class="source-line-no">078</span><span id="line-78"> *</span>
<span class="source-line-no">079</span><span id="line-79"> * A third variant allows you to select the type of exceptions you want to catch</span>
<span class="source-line-no">080</span><span id="line-80"> * (no verification involved):</span>
<span class="source-line-no">081</span><span id="line-81"> * &lt;code&gt;// catch IllegalArgumentExceptions but no other exceptions</span>
<span class="source-line-no">082</span><span id="line-82"> * catchException(customerService, IllegalArgumentException.class).prepareBilling(Prize.Zero);&lt;/code&gt;</span>
<span class="source-line-no">083</span><span id="line-83"> *</span>
<span class="source-line-no">084</span><span id="line-84"> * The fourth and last variant verifies that some exception is thrown, i.e. the</span>
<span class="source-line-no">085</span><span id="line-85"> * type of the exception does not matter:</span>
<span class="source-line-no">086</span><span id="line-86"> * &lt;code&gt;verifyException(customerService).prepareBilling(Prize.Zero);&lt;/code&gt;</span>
<span class="source-line-no">087</span><span id="line-87"> *</span>
<span class="source-line-no">088</span><span id="line-88"> * In all variants you can use &lt;code&gt;caughtException()&lt;/code&gt; afterwards to</span>
<span class="source-line-no">089</span><span id="line-89"> * inspect the caught exception.</span>
<span class="source-line-no">090</span><span id="line-90"> *</span>
<span class="source-line-no">091</span><span id="line-91"> * Finally, there some alternative ways to catch and verify exceptions:</span>
<span class="source-line-no">092</span><span id="line-92"> * &lt;ul&gt;</span>
<span class="source-line-no">093</span><span id="line-93"> * &lt;li&gt;{@link BDDCatchException} - a BDD-like approach,</span>
<span class="source-line-no">094</span><span id="line-94"> * &lt;li&gt; {@link CatchExceptionHamcrestMatchers} - Hamcrest assertions</span>
<span class="source-line-no">095</span><span id="line-95"> * &lt;/ul&gt;</span>
<span class="source-line-no">096</span><span id="line-96"> * &lt;strong&gt;2. What is this stuff actually good for?&lt;/strong&gt;</span>
<span class="source-line-no">097</span><span id="line-97"> *</span>
<span class="source-line-no">098</span><span id="line-98"> * This class targets concise and robust code in tests. Dadid Saff, a commiter</span>
<span class="source-line-no">099</span><span id="line-99"> * to JUnit, has &lt;a</span>
<span class="source-line-no">100</span><span id="line-100"> * href="http://shareandenjoy.saff.net/2006/12/assertthrownexception_20.html"</span>
<span class="source-line-no">101</span><span id="line-101"> * &gt;discussed&lt;/a&gt; this approach in 2007. Let me summarize the arguments here.</span>
<span class="source-line-no">102</span><span id="line-102"> *</span>
<span class="source-line-no">103</span><span id="line-103"> * There are two advantages of the approach proposed here in comparison to the</span>
<span class="source-line-no">104</span><span id="line-104"> * use of try/catch blocks.</span>
<span class="source-line-no">105</span><span id="line-105"> * &lt;ul&gt;</span>
<span class="source-line-no">106</span><span id="line-106"> * &lt;li&gt;The test is more concise and easier to read.</span>
<span class="source-line-no">107</span><span id="line-107"> * &lt;li&gt;The test cannot be corrupted by a missing assertion. Assume you forgot to</span>
<span class="source-line-no">108</span><span id="line-108"> * type &lt;code&gt;fail()&lt;/code&gt; behind the method call that is expected to throw an</span>
<span class="source-line-no">109</span><span id="line-109"> * exception.</span>
<span class="source-line-no">110</span><span id="line-110"> * &lt;/ul&gt;</span>
<span class="source-line-no">111</span><span id="line-111"> *</span>
<span class="source-line-no">112</span><span id="line-112"> * There are also some advantages of this approach in comparison to test</span>
<span class="source-line-no">113</span><span id="line-113"> * runner-specific mechanisms that catch and verify exceptions.</span>
<span class="source-line-no">114</span><span id="line-114"> * &lt;ul&gt;</span>
<span class="source-line-no">115</span><span id="line-115"> * &lt;li&gt;A single test can verify more than one thrown exception.</span>
<span class="source-line-no">116</span><span id="line-116"> * &lt;li&gt;The test can verify the properties of the thrown exception after the</span>
<span class="source-line-no">117</span><span id="line-117"> * exception is caught.</span>
<span class="source-line-no">118</span><span id="line-118"> * &lt;li&gt;The test can specify by which method call the exception must be thrown.</span>
<span class="source-line-no">119</span><span id="line-119"> * &lt;li&gt;The test does not depend on a specific test runner (JUnit4, TestNG).</span>
<span class="source-line-no">120</span><span id="line-120"> * &lt;/ul&gt;</span>
<span class="source-line-no">121</span><span id="line-121"> *</span>
<span class="source-line-no">122</span><span id="line-122"> * &lt;strong&gt;3. How does it work internally?&lt;/strong&gt;</span>
<span class="source-line-no">123</span><span id="line-123"> *</span>
<span class="source-line-no">124</span><span id="line-124"> * The method &lt;code&gt;catchException(obj)&lt;/code&gt; wraps the given object with a</span>
<span class="source-line-no">125</span><span id="line-125"> * proxy that catches the exception, then (optionally) verifies the exception,</span>
<span class="source-line-no">126</span><span id="line-126"> * and finally attaches the exception to the current &lt;a</span>
<span class="source-line-no">127</span><span id="line-127"> * id="threadlocal"&gt;thread&lt;/a&gt; for further analysis. The &lt;a</span>
<span class="source-line-no">128</span><span id="line-128"> * href="#proxies"&gt;known limitations&lt;/a&gt; for proxies apply.</span>
<span class="source-line-no">129</span><span id="line-129"> *</span>
<span class="source-line-no">130</span><span id="line-130"> * Is both memory consumption and runtime a concern for you? Then use try/catch</span>
<span class="source-line-no">131</span><span id="line-131"> * blocks instead of this class. Because in this case the creation of proxies is</span>
<span class="source-line-no">132</span><span id="line-132"> * an unnecessary overhead. If only either memory consumption or runtime is an</span>
<span class="source-line-no">133</span><span id="line-133"> * issue for you, feel free to configure the cache of the underlying proxy</span>
<span class="source-line-no">134</span><span id="line-134"> * factories as appropriate.</span>
<span class="source-line-no">135</span><span id="line-135"> * &lt;strong&gt;4. When is the caught exception reset?&lt;/strong&gt;</span>
<span class="source-line-no">136</span><span id="line-136"> *</span>
<span class="source-line-no">137</span><span id="line-137"> * The Method {@link #caughtException()} returns the exception thrown by the</span>
<span class="source-line-no">138</span><span id="line-138"> * last method call on a proxied object in the current thread, i.e. it is reset</span>
<span class="source-line-no">139</span><span id="line-139"> * by calling a method on the proxied object. If the called method has not</span>
<span class="source-line-no">140</span><span id="line-140"> * thrown an exception, &lt;code&gt;caughtException()&lt;/code&gt; returns null.</span>
<span class="source-line-no">141</span><span id="line-141"> *</span>
<span class="source-line-no">142</span><span id="line-142"> * To reset the caught exception manually, call {@link #resetCaughtException()}.</span>
<span class="source-line-no">143</span><span id="line-143"> * At the moment there is no way to reset exceptions that have been caught in</span>
<span class="source-line-no">144</span><span id="line-144"> * other threads.</span>
<span class="source-line-no">145</span><span id="line-145"> * &lt;strong&gt;5. My code throws a ClassCastException. Why?&lt;/strong&gt;</span>
<span class="source-line-no">146</span><span id="line-146"> *</span>
<span class="source-line-no">147</span><span id="line-147"> * Example:</span>
<span class="source-line-no">148</span><span id="line-148"> * &lt;code&gt;StringBuilder sb = new StringBuilder();</span>
<span class="source-line-no">149</span><span id="line-149"> * catchException(sb).charAt(-2); // throws ClassCastException&lt;/code&gt;</span>
<span class="source-line-no">150</span><span id="line-150"> *</span>
<span class="source-line-no">151</span><span id="line-151"> * Probably you have tested a final class. Proxy factories usually try to</span>
<span class="source-line-no">152</span><span id="line-152"> * subclass the type of the proxied object. This is not possible if the original</span>
<span class="source-line-no">153</span><span id="line-153"> * class is final. But there is a way out. If the tested method belongs to an</span>
<span class="source-line-no">154</span><span id="line-154"> * interface, then you can cast the argument (here: &lt;code&gt;sb&lt;/code&gt;) to that</span>
<span class="source-line-no">155</span><span id="line-155"> * interface or ,easier, change the declared type of the argument to the</span>
<span class="source-line-no">156</span><span id="line-156"> * interface type. This works because the created proxy is not longer required</span>
<span class="source-line-no">157</span><span id="line-157"> * to have the same type as the original class but it must only have the same</span>
<span class="source-line-no">158</span><span id="line-158"> * interface.</span>
<span class="source-line-no">159</span><span id="line-159"> * &lt;code&gt;// first variant</span>
<span class="source-line-no">160</span><span id="line-160"> * StringBuilder sb = new StringBuilder();</span>
<span class="source-line-no">161</span><span id="line-161"> * catchException((CharSequence) sb).charAt(-2); // works fine</span>
<span class="source-line-no">162</span><span id="line-162"> *</span>
<span class="source-line-no">163</span><span id="line-163"> * // second variant</span>
<span class="source-line-no">164</span><span id="line-164"> * CharSequence sb = new StringBuilder();</span>
<span class="source-line-no">165</span><span id="line-165"> * catchException(sb).charAt(-2); // works fine&lt;/code&gt; If the tested</span>
<span class="source-line-no">166</span><span id="line-166"> * method does no belong to an interface fall back to the try/catch-blocks or</span>
<span class="source-line-no">167</span><span id="line-167"> * use &lt;a</span>
<span class="source-line-no">168</span><span id="line-168"> * href="http://code.google.com/p/catch-exception/wiki/Dependencies"&gt;Powermock</span>
<span class="source-line-no">169</span><span id="line-169"> * &lt;/a&gt;.</span>
<span class="source-line-no">170</span><span id="line-170"> * &lt;code&gt;// example for</span>
<span class="source-line-no">171</span><span id="line-171"> * PowerMock with JUnit4</span>
<span class="source-line-no">172</span><span id="line-172"> * &amp;#064;RunWith(PowerMockRunner.class)</span>
<span class="source-line-no">173</span><span id="line-173"> * &amp;#064;PrepareForTest({ MyFinalType.class })</span>
<span class="source-line-no">174</span><span id="line-174"> * public class MyTest {</span>
<span class="source-line-no">175</span><span id="line-175"> * &lt;/code&gt;</span>
<span class="source-line-no">176</span><span id="line-176"> * &lt;strong&gt;6. Do I have to care about memory leaks?&lt;/strong&gt;</span>
<span class="source-line-no">177</span><span id="line-177"> *</span>
<span class="source-line-no">178</span><span id="line-178"> * This library uses a {@link ThreadLocal}. ThreadLocals are known to cause</span>
<span class="source-line-no">179</span><span id="line-179"> * memory leaks if they refer to a class the garbage collector would like to</span>
<span class="source-line-no">180</span><span id="line-180"> * collect. If you use this library only for testing, then memory leaks do not</span>
<span class="source-line-no">181</span><span id="line-181"> * worry you. If you use this library for other purposes than testing, you</span>
<span class="source-line-no">182</span><span id="line-182"> * should care.</span>
<span class="source-line-no">183</span><span id="line-183"> *</span>
<span class="source-line-no">184</span><span id="line-184"> * &lt;strong&gt;7. The caught exception is not available in another thread. Why?&lt;/strong&gt;</span>
<span class="source-line-no">185</span><span id="line-185"> *</span>
<span class="source-line-no">186</span><span id="line-186"> * The caught exception is saved &lt;a href="#threadlocal"&gt;at the thread&lt;/a&gt; the</span>
<span class="source-line-no">187</span><span id="line-187"> * exception is thrown in. This is the reason the exception is not visible</span>
<span class="source-line-no">188</span><span id="line-188"> * within any other thread.</span>
<span class="source-line-no">189</span><span id="line-189"> * &lt;strong&gt;8. Is there a way to get rid of the throws clause in my test</span>
<span class="source-line-no">190</span><span id="line-190"> * method?&lt;/strong&gt;</span>
<span class="source-line-no">191</span><span id="line-191"> *</span>
<span class="source-line-no">192</span><span id="line-192"> * Example:</span>
<span class="source-line-no">193</span><span id="line-193"> * &lt;code&gt;public void testSomething() throws Exception {</span>
<span class="source-line-no">194</span><span id="line-194"> * ...</span>
<span class="source-line-no">195</span><span id="line-195"> * catchException(obj).do(); // do() throws a checked exception&lt;/code&gt; No,</span>
<span class="source-line-no">196</span><span id="line-196"> * although the exception is always caught you cannot omit the throws clause in</span>
<span class="source-line-no">197</span><span id="line-197"> * your test method.</span>
<span class="source-line-no">198</span><span id="line-198"> * &lt;strong&gt;11. Can I catch errors instead of exceptions?&lt;/strong&gt;</span>
<span class="source-line-no">199</span><span id="line-199"> *</span>
<span class="source-line-no">200</span><span id="line-200"> * Yes, have a look at</span>
<span class="source-line-no">201</span><span id="line-201"> * {@code com.googlecode.catchexception.throwable.CatchThrowable} (in module</span>
<span class="source-line-no">202</span><span id="line-202"> * catch-throwable).</span>
<span class="source-line-no">203</span><span id="line-203"> *</span>
<span class="source-line-no">204</span><span id="line-204"> * @author rwoo</span>
<span class="source-line-no">205</span><span id="line-205"> * @since 16.09.2011</span>
<span class="source-line-no">206</span><span id="line-206"> */</span>
<span class="source-line-no">207</span><span id="line-207">public class CatchException {</span>
<span class="source-line-no">208</span><span id="line-208"></span>
<span class="source-line-no">209</span><span id="line-209">    /**</span>
<span class="source-line-no">210</span><span id="line-210">     * Returns the exception caught during the last call in the current thread.</span>
<span class="source-line-no">211</span><span id="line-211">     *</span>
<span class="source-line-no">212</span><span id="line-212">     * @param &lt;E&gt; This type parameter makes some type casts redundant.</span>
<span class="source-line-no">213</span><span id="line-213">     * @return Returns the exception caught during the last call in the current</span>
<span class="source-line-no">214</span><span id="line-214">     * thread - if the call was made through a proxy that has been created via</span>
<span class="source-line-no">215</span><span id="line-215">     * {@link #verifyException(ThrowingCallable, Class) verifyException()} or</span>
<span class="source-line-no">216</span><span id="line-216">     * {@link #catchException(ThrowingCallable, Class) catchException()}. Returns</span>
<span class="source-line-no">217</span><span id="line-217">     * null when no exception was caught.</span>
<span class="source-line-no">218</span><span id="line-218">     */</span>
<span class="source-line-no">219</span><span id="line-219">    public static &lt;E extends Exception&gt; E caughtException() {</span>
<span class="source-line-no">220</span><span id="line-220">        return ExceptionHolder.get();</span>
<span class="source-line-no">221</span><span id="line-221">    }</span>
<span class="source-line-no">222</span><span id="line-222"></span>
<span class="source-line-no">223</span><span id="line-223">    public static &lt;E extends Exception&gt; E caughtException(Class&lt;E&gt; caughtExceptionType) {</span>
<span class="source-line-no">224</span><span id="line-224">        return ExceptionHolder.get();</span>
<span class="source-line-no">225</span><span id="line-225">    }</span>
<span class="source-line-no">226</span><span id="line-226"></span>
<span class="source-line-no">227</span><span id="line-227">    /**</span>
<span class="source-line-no">228</span><span id="line-228">     * Use it to verify that an exception is thrown and to get access to the</span>
<span class="source-line-no">229</span><span id="line-229">     * thrown exception (for further verifications).</span>
<span class="source-line-no">230</span><span id="line-230">     *</span>
<span class="source-line-no">231</span><span id="line-231">     * The following example verifies that obj.doX() throws a Exception:</span>
<span class="source-line-no">232</span><span id="line-232">     * &lt;code&gt;verifyException(obj).doX(); // catch and verify</span>
<span class="source-line-no">233</span><span id="line-233">     * assert "foobar".equals(caughtException().getMessage()); // further analysis</span>
<span class="source-line-no">234</span><span id="line-234">     * &lt;/code&gt;</span>
<span class="source-line-no">235</span><span id="line-235">     *</span>
<span class="source-line-no">236</span><span id="line-236">     * If &lt;code&gt;doX()&lt;/code&gt; does not throw a &lt;code&gt;Exception&lt;/code&gt;, then a</span>
<span class="source-line-no">237</span><span id="line-237">     * {@link ExceptionNotThrownAssertionError} is thrown. Otherwise the thrown</span>
<span class="source-line-no">238</span><span id="line-238">     * exception can be retrieved via {@link #caughtException()}.</span>
<span class="source-line-no">239</span><span id="line-239">     *</span>
<span class="source-line-no">240</span><span id="line-240">     *</span>
<span class="source-line-no">241</span><span id="line-241">     * @param actor The instance that shall be proxied. Must not be</span>
<span class="source-line-no">242</span><span id="line-242">     *              &lt;code&gt;null&lt;/code&gt;.</span>
<span class="source-line-no">243</span><span id="line-243">     */</span>
<span class="source-line-no">244</span><span id="line-244">    public static void verifyException(ThrowingCallable actor) {</span>
<span class="source-line-no">245</span><span id="line-245">        verifyException(actor, Exception.class);</span>
<span class="source-line-no">246</span><span id="line-246">    }</span>
<span class="source-line-no">247</span><span id="line-247"></span>
<span class="source-line-no">248</span><span id="line-248">    /**</span>
<span class="source-line-no">249</span><span id="line-249">     * Use it to verify that an exception of specific type is thrown and to get</span>
<span class="source-line-no">250</span><span id="line-250">     * access to the thrown exception (for further verifications).</span>
<span class="source-line-no">251</span><span id="line-251">     *</span>
<span class="source-line-no">252</span><span id="line-252">     * The following example verifies that obj.doX() throws a MyException:</span>
<span class="source-line-no">253</span><span id="line-253">     * &lt;code&gt;verifyException(obj, MyException.class).doX(); // catch and verify</span>
<span class="source-line-no">254</span><span id="line-254">     * assert "foobar".equals(caughtException().getMessage()); // further analysis</span>
<span class="source-line-no">255</span><span id="line-255">     * &lt;/code&gt;</span>
<span class="source-line-no">256</span><span id="line-256">     *</span>
<span class="source-line-no">257</span><span id="line-257">     * If &lt;code&gt;doX()&lt;/code&gt; does not throw a &lt;code&gt;MyException&lt;/code&gt;, then a</span>
<span class="source-line-no">258</span><span id="line-258">     * {@link ExceptionNotThrownAssertionError} is thrown. Otherwise the thrown</span>
<span class="source-line-no">259</span><span id="line-259">     * exception can be retrieved via {@link #caughtException()}.</span>
<span class="source-line-no">260</span><span id="line-260">     *</span>
<span class="source-line-no">261</span><span id="line-261">     *</span>
<span class="source-line-no">262</span><span id="line-262">     * @param actor The instance that shall be proxied. Must not be</span>
<span class="source-line-no">263</span><span id="line-263">     *              &lt;code&gt;null&lt;/code&gt;.</span>
<span class="source-line-no">264</span><span id="line-264">     * @param clazz The type of the exception that shall be thrown by the</span>
<span class="source-line-no">265</span><span id="line-265">     *              underlying object. Must not be &lt;code&gt;null&lt;/code&gt;.</span>
<span class="source-line-no">266</span><span id="line-266">     */</span>
<span class="source-line-no">267</span><span id="line-267">    public static void verifyException(ThrowingCallable actor, Class&lt;? extends Exception&gt; clazz) {</span>
<span class="source-line-no">268</span><span id="line-268">        validateArguments(actor, clazz);</span>
<span class="source-line-no">269</span><span id="line-269">        catchException(actor, clazz, true);</span>
<span class="source-line-no">270</span><span id="line-270">    }</span>
<span class="source-line-no">271</span><span id="line-271"></span>
<span class="source-line-no">272</span><span id="line-272">    /**</span>
<span class="source-line-no">273</span><span id="line-273">     * Use it to catch an exception and to get access to the thrown exception</span>
<span class="source-line-no">274</span><span id="line-274">     * (for further verifications).</span>
<span class="source-line-no">275</span><span id="line-275">     *</span>
<span class="source-line-no">276</span><span id="line-276">     * In the following example you catch exceptions that are thrown by</span>
<span class="source-line-no">277</span><span id="line-277">     * obj.doX():</span>
<span class="source-line-no">278</span><span id="line-278">     * &lt;code&gt;catchException(obj).doX(); // catch</span>
<span class="source-line-no">279</span><span id="line-279">     * if (caughtException() != null) {</span>
<span class="source-line-no">280</span><span id="line-280">     * assert "foobar".equals(caughtException().getMessage()); // further analysis</span>
<span class="source-line-no">281</span><span id="line-281">     * }&lt;/code&gt;</span>
<span class="source-line-no">282</span><span id="line-282">     * If &lt;code&gt;doX()&lt;/code&gt; throws a exception, then {@link #caughtException()}</span>
<span class="source-line-no">283</span><span id="line-283">     * will return the caught exception. If &lt;code&gt;doX()&lt;/code&gt; does not throw a</span>
<span class="source-line-no">284</span><span id="line-284">     * exception, then {@link #caughtException()} will return &lt;code&gt;null&lt;/code&gt;.</span>
<span class="source-line-no">285</span><span id="line-285">     *</span>
<span class="source-line-no">286</span><span id="line-286">     *</span>
<span class="source-line-no">287</span><span id="line-287">     * @param actor The instance that shall be proxied. Must not be</span>
<span class="source-line-no">288</span><span id="line-288">     *              &lt;code&gt;null&lt;/code&gt;.</span>
<span class="source-line-no">289</span><span id="line-289">     */</span>
<span class="source-line-no">290</span><span id="line-290">    public static void catchException(com.googlecode.catchexception.ThrowingCallable actor) {</span>
<span class="source-line-no">291</span><span id="line-291">        validateArguments(actor, Exception.class);</span>
<span class="source-line-no">292</span><span id="line-292">        catchException(actor, Exception.class, false);</span>
<span class="source-line-no">293</span><span id="line-293">    }</span>
<span class="source-line-no">294</span><span id="line-294"></span>
<span class="source-line-no">295</span><span id="line-295">    /**</span>
<span class="source-line-no">296</span><span id="line-296">     * Use it to catch an exception of a specific type and to get access to the</span>
<span class="source-line-no">297</span><span id="line-297">     * thrown exception (for further verifications).</span>
<span class="source-line-no">298</span><span id="line-298">     *</span>
<span class="source-line-no">299</span><span id="line-299">     * In the following example you catch exceptions of type MyException that</span>
<span class="source-line-no">300</span><span id="line-300">     * are thrown by obj.doX():</span>
<span class="source-line-no">301</span><span id="line-301">     * &lt;code&gt;catchException(obj, MyException.class).doX(); // catch</span>
<span class="source-line-no">302</span><span id="line-302">     * if (caughtException() != null) {</span>
<span class="source-line-no">303</span><span id="line-303">     * assert "foobar".equals(caughtException().getMessage()); // further analysis</span>
<span class="source-line-no">304</span><span id="line-304">     * }&lt;/code&gt;</span>
<span class="source-line-no">305</span><span id="line-305">     * If &lt;code&gt;doX()&lt;/code&gt; throws a &lt;code&gt;MyException&lt;/code&gt;, then</span>
<span class="source-line-no">306</span><span id="line-306">     * {@link #caughtException()} will return the caught exception. If</span>
<span class="source-line-no">307</span><span id="line-307">     * &lt;code&gt;doX()&lt;/code&gt; does not throw a &lt;code&gt;MyException&lt;/code&gt;, then</span>
<span class="source-line-no">308</span><span id="line-308">     * {@link #caughtException()} will return &lt;code&gt;null&lt;/code&gt;. If</span>
<span class="source-line-no">309</span><span id="line-309">     * &lt;code&gt;doX()&lt;/code&gt; throws an exception of another type, i.e. not a</span>
<span class="source-line-no">310</span><span id="line-310">     * subclass but another class, then this exception is not thrown and</span>
<span class="source-line-no">311</span><span id="line-311">     * {@link #caughtException()} will return &lt;code&gt;null&lt;/code&gt;.</span>
<span class="source-line-no">312</span><span id="line-312">     *</span>
<span class="source-line-no">313</span><span id="line-313">     *</span>
<span class="source-line-no">314</span><span id="line-314">     * @param actor The instance that shall be proxied. Must not be</span>
<span class="source-line-no">315</span><span id="line-315">     *              &lt;code&gt;null&lt;/code&gt;.</span>
<span class="source-line-no">316</span><span id="line-316">     * @param clazz The type of the exception that shall be caught. Must not be</span>
<span class="source-line-no">317</span><span id="line-317">     *              &lt;code&gt;null&lt;/code&gt;.</span>
<span class="source-line-no">318</span><span id="line-318">     */</span>
<span class="source-line-no">319</span><span id="line-319">    public static void catchException(ThrowingCallable actor, Class&lt;? extends Exception&gt; clazz) {</span>
<span class="source-line-no">320</span><span id="line-320">        validateArguments(actor, clazz);</span>
<span class="source-line-no">321</span><span id="line-321">        catchException(actor, clazz, false);</span>
<span class="source-line-no">322</span><span id="line-322">    }</span>
<span class="source-line-no">323</span><span id="line-323"></span>
<span class="source-line-no">324</span><span id="line-324">    private static void catchException(ThrowingCallable actor, Class&lt;? extends Exception&gt; clazz,</span>
<span class="source-line-no">325</span><span id="line-325">                                       boolean assertException) {</span>
<span class="source-line-no">326</span><span id="line-326">        resetCaughtException();</span>
<span class="source-line-no">327</span><span id="line-327">        Exception exception = ExceptionCaptor.captureThrowable(actor);</span>
<span class="source-line-no">328</span><span id="line-328">        if (exception == null) {</span>
<span class="source-line-no">329</span><span id="line-329">            if (!assertException) {</span>
<span class="source-line-no">330</span><span id="line-330">                return;</span>
<span class="source-line-no">331</span><span id="line-331">            } else {</span>
<span class="source-line-no">332</span><span id="line-332">                throw new ExceptionNotThrownAssertionError(clazz);</span>
<span class="source-line-no">333</span><span id="line-333">            }</span>
<span class="source-line-no">334</span><span id="line-334">        }</span>
<span class="source-line-no">335</span><span id="line-335">        // is the thrown exception of the expected type?</span>
<span class="source-line-no">336</span><span id="line-336">        if (clazz.isAssignableFrom(exception.getClass())) {</span>
<span class="source-line-no">337</span><span id="line-337">            ExceptionHolder.set(exception);</span>
<span class="source-line-no">338</span><span id="line-338">        } else {</span>
<span class="source-line-no">339</span><span id="line-339">            if (assertException) {</span>
<span class="source-line-no">340</span><span id="line-340">                throw new ExceptionNotThrownAssertionError(clazz, exception);</span>
<span class="source-line-no">341</span><span id="line-341">            } else {</span>
<span class="source-line-no">342</span><span id="line-342">                ExceptionUtil.sneakyThrow(exception);</span>
<span class="source-line-no">343</span><span id="line-343">            }</span>
<span class="source-line-no">344</span><span id="line-344">        }</span>
<span class="source-line-no">345</span><span id="line-345">    }</span>
<span class="source-line-no">346</span><span id="line-346"></span>
<span class="source-line-no">347</span><span id="line-347">    private static void validateArguments(ThrowingCallable actor, Class&lt;? extends Exception&gt; clazz) {</span>
<span class="source-line-no">348</span><span id="line-348">        if (actor == null) throw new IllegalArgumentException("obj must not be null");</span>
<span class="source-line-no">349</span><span id="line-349">        if (clazz == null) throw new IllegalArgumentException("exceptionClazz must not be null");</span>
<span class="source-line-no">350</span><span id="line-350">    }</span>
<span class="source-line-no">351</span><span id="line-351"></span>
<span class="source-line-no">352</span><span id="line-352">    /**</span>
<span class="source-line-no">353</span><span id="line-353">     * Sets the {@link #caughtException() caught exception} to null. This does</span>
<span class="source-line-no">354</span><span id="line-354">     * not affect exceptions saved at threads other than the current one.</span>
<span class="source-line-no">355</span><span id="line-355">     *</span>
<span class="source-line-no">356</span><span id="line-356">     * Actually you probably never need to call this method because each method</span>
<span class="source-line-no">357</span><span id="line-357">     * call on a proxied object in the current thread resets the caught</span>
<span class="source-line-no">358</span><span id="line-358">     * exception. But if you want to improve test isolation or if you want to</span>
<span class="source-line-no">359</span><span id="line-359">     * 'clean up' after testing (to avoid memory leaks), call the method before</span>
<span class="source-line-no">360</span><span id="line-360">     * or after testing.</span>
<span class="source-line-no">361</span><span id="line-361">     */</span>
<span class="source-line-no">362</span><span id="line-362">    public static void resetCaughtException() {</span>
<span class="source-line-no">363</span><span id="line-363">        ExceptionHolder.set(null);</span>
<span class="source-line-no">364</span><span id="line-364">    }</span>
<span class="source-line-no">365</span><span id="line-365"></span>
<span class="source-line-no">366</span><span id="line-366">}</span>




























































</pre>
</div>
</main>
</body>
</html>