<!DOCTYPE HTML>
<!-- NewPage -->
<html lang="en">
<head>
<!-- Generated by javadoc -->
<title>CatchException (catch-exception-project 2.2.0 API)</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="../../../stylesheet.css" title="Style">
<link rel="stylesheet" type="text/css" href="../../../jquery/jquery-ui.min.css" title="Style">
<link rel="stylesheet" type="text/css" href="../../../jquery-ui.overrides.css" title="Style">
<script type="text/javascript" src="../../../script.js"></script>
<script type="text/javascript" src="../../../jquery/jszip/dist/jszip.min.js"></script>
<script type="text/javascript" src="../../../jquery/jszip-utils/dist/jszip-utils.min.js"></script>
<!--[if IE]>
<script type="text/javascript" src="../../../jquery/jszip-utils/dist/jszip-utils-ie.min.js"></script>
<![endif]-->
<script type="text/javascript" src="../../../jquery/jquery-3.6.1.min.js"></script>
<script type="text/javascript" src="../../../jquery/jquery-ui.min.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="CatchException (catch-exception-project 2.2.0 API)";
        }
    }
    catch(err) {
    }
//-->
var data = {"i0":9,"i1":9,"i2":9,"i3":9,"i4":9,"i5":9,"i6":9};
var tabs = {65535:["t0","All Methods"],1:["t1","Static Methods"],8:["t4","Concrete Methods"]};
var altColor = "altColor";
var rowColor = "rowColor";
var tableTab = "tableTab";
var activeTableTab = "activeTableTab";
var pathtoroot = "../../../";
var useModuleDirectories = true;
loadScripts(document, 'script');</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<header role="banner">
<nav role="navigation">
<div class="fixedNav">
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a id="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a id="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../index.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="class-use/CatchException.html">Use</a></li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../index-all.html">Index</a></li>
<li><a href="../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList" id="allclasses_navbar_top">
<li><a href="../../../allclasses.html">All&nbsp;Classes</a></li>
</ul>
<ul class="navListSearch">
<li><label for="search">SEARCH:</label>
<input type="text" id="search" value="search" disabled="disabled">
<input type="reset" id="reset" value="reset" disabled="disabled">
</li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor.summary">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor.detail">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a id="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
</div>
<div class="navPadding">&nbsp;</div>
<script type="text/javascript"><!--
$('.navPadding').css('padding-top', $('.fixedNav').css("height"));
//-->
</script>
</nav>
</header>
<!-- ======== START OF CLASS DATA ======== -->
<main role="main">
<div class="header">
<div class="subTitle"><span class="packageLabelInType">Package</span>&nbsp;<a href="package-summary.html">com.googlecode.catchexception</a></div>
<h2 title="Class CatchException" class="title">Class CatchException</h2>
</div>
<div class="contentContainer">
<ul class="inheritance">
<li><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang" class="externalLink">java.lang.Object</a></li>
<li>
<ul class="inheritance">
<li>com.googlecode.catchexception.CatchException</li>
</ul>
</li>
</ul>
<div class="description">
<ul class="blockList">
<li class="blockList">
<hr>
<pre>public class <span class="typeNameLabel">CatchException</span>
extends <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang" class="externalLink">Object</a></pre>
<div class="block">The methods of this class catch and verify exceptions in <em>a single line of code</em> and make them available for
 further analysis. This Javadoc content is also available on the
 <a href="http://code.google.com/p/catch-exception/">catch-exception</a> web page. <strong>Documentation</strong> <b>
 <a href="#1">1. How to use catch-exception?</a> <a href="#2">2. What is this stuff actually good for?</a>
 <a href="#3">3. How does it work internally?</a> <a href="#4">4. When is the caught exception reset?</a>
 <a href="#5">5. My code throws a ClassCastException. Why?</a> <a href="#6">6. The exception is not caught. Why?</a>
 <a href="#7">7. Do I have to care about memory leaks?</a> <a href="#8">8. The caught exception is not available in
 another thread. Why?</a> <a href="#9">9. How do I catch an exception thrown by a static method?</a> <a href="#11">11.
 Can I catch errors instead of exceptions?</a> </b> <strong>1. How to use catch-exception?</strong> The most basic
 usage is: <code>import static com.googlecode.catchexception.CatchException.*;

 // call customerService.prepareBilling(Prize.Zero)
 // and catch the exception if any is thrown
 catchException(customerService).prepareBilling(Prize.Zero);

 // assert that an IllegalArgumentException was thrown
 assert caughtException() instanceof IllegalArgumentException;</code> You can combine the two lines of code in a
 single one if you like: <code>// call customerService.prepareBilling(Prize.Zero)
 // and throw an ExceptionNotThrownAssertionError if
 // the expected exception is not thrown
 verifyException(customerService, IllegalArgumentException.class).prepareBilling(Prize.Zero);</code> There is a minor
 difference between both variants. In the first variant you must start the JVM with option <code>-ea</code> to enable
 the assertion. The second variant does not use JDK assertions and ,therefore, always verifies the caught exception. A
 third variant allows you to select the type of exceptions you want to catch (no verification involved):
 <code>// catch IllegalArgumentExceptions but no other exceptions
 catchException(customerService, IllegalArgumentException.class).prepareBilling(Prize.Zero);</code> The fourth and
 last variant verifies that some exception is thrown, i.e. the type of the exception does not matter:
 <code>verifyException(customerService).prepareBilling(Prize.Zero);</code> In all variants you can use
 <code>caughtException()</code> afterwards to inspect the caught exception. Finally, there some alternative ways to
 catch and verify exceptions:
 <ul>
 <li><a href="apis/BDDCatchException.html" title="class in com.googlecode.catchexception.apis"><code>BDDCatchException</code></a> - a BDD-like approach,
 <li><a href="apis/CatchExceptionHamcrestMatchers.html" title="class in com.googlecode.catchexception.apis"><code>CatchExceptionHamcrestMatchers</code></a> - Hamcrest assertions
 </ul>
 <strong>2. What is this stuff actually good for?</strong> This class targets concise and robust code in tests. Dadid
 Saff, a commiter to JUnit, has
 <a href="http://shareandenjoy.saff.net/2006/12/assertthrownexception_20.html">discussed</a> this approach in 2007.
 Let me summarize the arguments here. There are two advantages of the approach proposed here in comparison to the use
 of try/catch blocks.
 <ul>
 <li>The test is more concise and easier to read.
 <li>The test cannot be corrupted by a missing assertion. Assume you forgot to type <code>fail()</code> behind the
 method call that is expected to throw an exception.
 </ul>
 There are also some advantages of this approach in comparison to test runner-specific mechanisms that catch and
 verify exceptions.
 <ul>
 <li>A single test can verify more than one thrown exception.
 <li>The test can verify the properties of the thrown exception after the exception is caught.
 <li>The test can specify by which method call the exception must be thrown.
 <li>The test does not depend on a specific test runner (JUnit4, TestNG).
 </ul>
 <strong>3. How does it work internally?</strong> The method <code>catchException(obj)</code> wraps the given object
 with a proxy that catches the exception, then (optionally) verifies the exception, and finally attaches the exception
 to the current <a id="threadlocal">thread</a> for further analysis. The <a href="#proxies">known limitations</a> for
 proxies apply. Is both memory consumption and runtime a concern for you? Then use try/catch blocks instead of this
 class. Because in this case the creation of proxies is an unnecessary overhead. If only either memory consumption or
 runtime is an issue for you, feel free to configure the cache of the underlying proxy factories as appropriate.
 <strong>4. When is the caught exception reset?</strong> The Method <a href="#caughtException()"><code>caughtException()</code></a> returns the exception
 thrown by the last method call on a proxied object in the current thread, i.e. it is reset by calling a method on the
 proxied object. If the called method has not thrown an exception, <code>caughtException()</code> returns null. To
 reset the caught exception manually, call <a href="#resetCaughtException()"><code>resetCaughtException()</code></a>. At the moment there is no way to reset
 exceptions that have been caught in other threads. <strong>5. My code throws a ClassCastException. Why?</strong>
 Example: <code>StringBuilder sb = new StringBuilder();
 catchException(sb).charAt(-2); // throws ClassCastException</code> Probably you have tested a final class. Proxy
 factories usually try to subclass the type of the proxied object. This is not possible if the original class is
 final. But there is a way out. If the tested method belongs to an interface, then you can cast the argument (here:
 <code>sb</code>) to that interface or ,easier, change the declared type of the argument to the interface type. This
 works because the created proxy is not longer required to have the same type as the original class but it must only
 have the same interface. <code>// first variant
 StringBuilder sb = new StringBuilder();
 catchException((CharSequence) sb).charAt(-2); // works fine

 // second variant
 CharSequence sb = new StringBuilder();
 catchException(sb).charAt(-2); // works fine</code> If the tested method does no belong to an interface fall back to
 the try/catch-blocks or use <a href="http://code.google.com/p/catch-exception/wiki/Dependencies">Powermock </a>.
 <code>// example for
 PowerMock with JUnit4
 &#064;RunWith(PowerMockRunner.class)
 &#064;PrepareForTest({ MyFinalType.class })
 public class MyTest {
 </code> <strong>6. Do I have to care about memory leaks?</strong> This library uses a <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadLocal.html?is-external=true" title="class or interface in java.lang" class="externalLink"><code>ThreadLocal</code></a>.
 ThreadLocals are known to cause memory leaks if they refer to a class the garbage collector would like to collect. If
 you use this library only for testing, then memory leaks do not worry you. If you use this library for other purposes
 than testing, you should care. <strong>7. The caught exception is not available in another thread. Why?</strong> The
 caught exception is saved <a href="#threadlocal">at the thread</a> the exception is thrown in. This is the reason the
 exception is not visible within any other thread. <strong>8. Is there a way to get rid of the throws clause in my
 test method?</strong> Example: <code>public void testSomething() throws Exception {
 ...
 catchException(obj).do(); // do() throws a checked exception</code> No, although the exception is always caught you
 cannot omit the throws clause in your test method. <strong>11. Can I catch errors instead of exceptions?</strong>
 Yes, have a look at <code>com.googlecode.catchexception.throwable.CatchThrowable</code> (in module catch-throwable).</div>
</li>
</ul>
</div>
<div class="summary">
<ul class="blockList">
<li class="blockList">
<!-- ======== CONSTRUCTOR SUMMARY ======== -->
<section>
<ul class="blockList">
<li class="blockList"><a id="constructor.summary">
<!--   -->
</a>
<h3>Constructor Summary</h3>
<table class="memberSummary">
<caption><span>Constructors</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Constructor</th>
<th class="colLast" scope="col">Description</th>
</tr>
<tr class="altColor">
<th class="colConstructorName" scope="row"><code><span class="memberNameLink"><a href="#%3Cinit%3E()">CatchException</a></span>()</code></th>
<td class="colLast">&nbsp;</td>
</tr>
</table>
</li>
</ul>
</section>
<!-- ========== METHOD SUMMARY =========== -->
<section>
<ul class="blockList">
<li class="blockList"><a id="method.summary">
<!--   -->
</a>
<h3>Method Summary</h3>
<table class="memberSummary">
<caption><span id="t0" class="activeTableTab"><span>All Methods</span><span class="tabEnd">&nbsp;</span></span><span id="t1" class="tableTab"><span><a href="javascript:show(1);">Static Methods</a></span><span class="tabEnd">&nbsp;</span></span><span id="t4" class="tableTab"><span><a href="javascript:show(8);">Concrete Methods</a></span><span class="tabEnd">&nbsp;</span></span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colSecond" scope="col">Method</th>
<th class="colLast" scope="col">Description</th>
</tr>
<tr id="i0" class="altColor">
<td class="colFirst"><code>static void</code></td>
<th class="colSecond" scope="row"><code><span class="memberNameLink"><a href="#catchException(com.googlecode.catchexception.ThrowingCallable)">catchException</a></span>&#8203;(<a href="ThrowingCallable.html" title="interface in com.googlecode.catchexception">ThrowingCallable</a>&nbsp;actor)</code></th>
<td class="colLast">
<div class="block">Use it to catch an exception and to get access to the thrown exception (for further verifications).</div>
</td>
</tr>
<tr id="i1" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<th class="colSecond" scope="row"><code><span class="memberNameLink"><a href="#catchException(com.googlecode.catchexception.ThrowingCallable,java.lang.Class)">catchException</a></span>&#8203;(<a href="ThrowingCallable.html" title="interface in com.googlecode.catchexception">ThrowingCallable</a>&nbsp;actor,
              <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang" class="externalLink">Class</a>&lt;? extends <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang" class="externalLink">Exception</a>&gt;&nbsp;clazz)</code></th>
<td class="colLast">
<div class="block">Use it to catch an exception of a specific type and to get access to the thrown exception (for further
 verifications).</div>
</td>
</tr>
<tr id="i2" class="altColor">
<td class="colFirst"><code>static &lt;E extends <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang" class="externalLink">Exception</a>&gt;<br>E</code></td>
<th class="colSecond" scope="row"><code><span class="memberNameLink"><a href="#caughtException()">caughtException</a></span>()</code></th>
<td class="colLast">
<div class="block">Returns the exception caught during the last call in the current thread.</div>
</td>
</tr>
<tr id="i3" class="rowColor">
<td class="colFirst"><code>static &lt;E extends <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang" class="externalLink">Exception</a>&gt;<br>E</code></td>
<th class="colSecond" scope="row"><code><span class="memberNameLink"><a href="#caughtException(java.lang.Class)">caughtException</a></span>&#8203;(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang" class="externalLink">Class</a>&lt;E&gt;&nbsp;caughtExceptionType)</code></th>
<td class="colLast">&nbsp;</td>
</tr>
<tr id="i4" class="altColor">
<td class="colFirst"><code>static void</code></td>
<th class="colSecond" scope="row"><code><span class="memberNameLink"><a href="#resetCaughtException()">resetCaughtException</a></span>()</code></th>
<td class="colLast">
<div class="block">Sets the <a href="#caughtException()"><code>caught exception</code></a> to null.</div>
</td>
</tr>
<tr id="i5" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<th class="colSecond" scope="row"><code><span class="memberNameLink"><a href="#verifyException(com.googlecode.catchexception.ThrowingCallable)">verifyException</a></span>&#8203;(<a href="ThrowingCallable.html" title="interface in com.googlecode.catchexception">ThrowingCallable</a>&nbsp;actor)</code></th>
<td class="colLast">
<div class="block">Use it to verify that an exception is thrown and to get access to the thrown exception (for further
 verifications).</div>
</td>
</tr>
<tr id="i6" class="altColor">
<td class="colFirst"><code>static void</code></td>
<th class="colSecond" scope="row"><code><span class="memberNameLink"><a href="#verifyException(com.googlecode.catchexception.ThrowingCallable,java.lang.Class)">verifyException</a></span>&#8203;(<a href="ThrowingCallable.html" title="interface in com.googlecode.catchexception">ThrowingCallable</a>&nbsp;actor,
               <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang" class="externalLink">Class</a>&lt;? extends <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang" class="externalLink">Exception</a>&gt;&nbsp;clazz)</code></th>
<td class="colLast">
<div class="block">Use it to verify that an exception of specific type is thrown and to get access to the thrown exception (for
 further verifications).</div>
</td>
</tr>
</table>
<ul class="blockList">
<li class="blockList"><a id="methods.inherited.from.class.java.lang.Object">
<!--   -->
</a>
<h3>Methods inherited from class&nbsp;java.lang.<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang" class="externalLink">Object</a></h3>
<code><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#clone()" title="class or interface in java.lang" class="externalLink">clone</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#equals(java.lang.Object)" title="class or interface in java.lang" class="externalLink">equals</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#finalize()" title="class or interface in java.lang" class="externalLink">finalize</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#getClass()" title="class or interface in java.lang" class="externalLink">getClass</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#hashCode()" title="class or interface in java.lang" class="externalLink">hashCode</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#notify()" title="class or interface in java.lang" class="externalLink">notify</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#notifyAll()" title="class or interface in java.lang" class="externalLink">notifyAll</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#toString()" title="class or interface in java.lang" class="externalLink">toString</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#wait()" title="class or interface in java.lang" class="externalLink">wait</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#wait(long)" title="class or interface in java.lang" class="externalLink">wait</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#wait(long,int)" title="class or interface in java.lang" class="externalLink">wait</a></code></li>
</ul>
</li>
</ul>
</section>
</li>
</ul>
</div>
<div class="details">
<ul class="blockList">
<li class="blockList">
<!-- ========= CONSTRUCTOR DETAIL ======== -->
<section>
<ul class="blockList">
<li class="blockList"><a id="constructor.detail">
<!--   -->
</a>
<h3>Constructor Detail</h3>
<a id="&lt;init&gt;()">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>CatchException</h4>
<pre>public&nbsp;CatchException()</pre>
</li>
</ul>
</li>
</ul>
</section>
<!-- ============ METHOD DETAIL ========== -->
<section>
<ul class="blockList">
<li class="blockList"><a id="method.detail">
<!--   -->
</a>
<h3>Method Detail</h3>
<a id="caughtException()">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>caughtException</h4>
<pre class="methodSignature">public static&nbsp;&lt;E extends <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang" class="externalLink">Exception</a>&gt;&nbsp;E&nbsp;caughtException()</pre>
<div class="block">Returns the exception caught during the last call in the current thread.</div>
<dl>
<dt><span class="paramLabel">Type Parameters:</span></dt>
<dd><code>E</code> - This type parameter makes some type casts redundant.</dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>Returns the exception caught during the last call in the current thread - if the call was made through a
         proxy that has been created via <a href="#verifyException(com.googlecode.catchexception.ThrowingCallable,java.lang.Class)"><code>verifyException()</code></a> or
         <a href="#catchException(com.googlecode.catchexception.ThrowingCallable,java.lang.Class)"><code>catchException()</code></a>. Returns null when no exception was
         caught.</dd>
</dl>
</li>
</ul>
<a id="caughtException(java.lang.Class)">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>caughtException</h4>
<pre class="methodSignature">public static&nbsp;&lt;E extends <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang" class="externalLink">Exception</a>&gt;&nbsp;E&nbsp;caughtException&#8203;(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang" class="externalLink">Class</a>&lt;E&gt;&nbsp;caughtExceptionType)</pre>
</li>
</ul>
<a id="verifyException(com.googlecode.catchexception.ThrowingCallable)">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>verifyException</h4>
<pre class="methodSignature">public static&nbsp;void&nbsp;verifyException&#8203;(<a href="ThrowingCallable.html" title="interface in com.googlecode.catchexception">ThrowingCallable</a>&nbsp;actor)</pre>
<div class="block">Use it to verify that an exception is thrown and to get access to the thrown exception (for further
 verifications). The following example verifies that obj.doX() throws a Exception:
 <code>verifyException(obj).doX(); // catch and verify
 assert "foobar".equals(caughtException().getMessage()); // further analysis
 </code> If <code>doX()</code> does not throw a <code>Exception</code>, then a
 <a href="ExceptionNotThrownAssertionError.html" title="class in com.googlecode.catchexception"><code>ExceptionNotThrownAssertionError</code></a> is thrown. Otherwise the thrown exception can be retrieved via
 <a href="#caughtException()"><code>caughtException()</code></a>.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>actor</code> - The instance that shall be proxied. Must not be <code>null</code>.</dd>
</dl>
</li>
</ul>
<a id="verifyException(com.googlecode.catchexception.ThrowingCallable,java.lang.Class)">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>verifyException</h4>
<pre class="methodSignature">public static&nbsp;void&nbsp;verifyException&#8203;(<a href="ThrowingCallable.html" title="interface in com.googlecode.catchexception">ThrowingCallable</a>&nbsp;actor,
                                   <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang" class="externalLink">Class</a>&lt;? extends <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang" class="externalLink">Exception</a>&gt;&nbsp;clazz)</pre>
<div class="block">Use it to verify that an exception of specific type is thrown and to get access to the thrown exception (for
 further verifications). The following example verifies that obj.doX() throws a MyException:
 <code>verifyException(obj, MyException.class).doX(); // catch and verify
 assert "foobar".equals(caughtException().getMessage()); // further analysis
 </code> If <code>doX()</code> does not throw a <code>MyException</code>, then a
 <a href="ExceptionNotThrownAssertionError.html" title="class in com.googlecode.catchexception"><code>ExceptionNotThrownAssertionError</code></a> is thrown. Otherwise the thrown exception can be retrieved via
 <a href="#caughtException()"><code>caughtException()</code></a>.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>actor</code> - The instance that shall be proxied. Must not be <code>null</code>.</dd>
<dd><code>clazz</code> - The type of the exception that shall be thrown by the underlying object. Must not be
            <code>null</code>.</dd>
</dl>
</li>
</ul>
<a id="catchException(com.googlecode.catchexception.ThrowingCallable)">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>catchException</h4>
<pre class="methodSignature">public static&nbsp;void&nbsp;catchException&#8203;(<a href="ThrowingCallable.html" title="interface in com.googlecode.catchexception">ThrowingCallable</a>&nbsp;actor)</pre>
<div class="block">Use it to catch an exception and to get access to the thrown exception (for further verifications). In the
 following example you catch exceptions that are thrown by obj.doX(): <code>catchException(obj).doX(); // catch
 if (caughtException() != null) {
 assert "foobar".equals(caughtException().getMessage()); // further analysis
 }</code> If <code>doX()</code> throws a exception, then <a href="#caughtException()"><code>caughtException()</code></a> will return the caught
 exception. If <code>doX()</code> does not throw a exception, then <a href="#caughtException()"><code>caughtException()</code></a> will return
 <code>null</code>.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>actor</code> - The instance that shall be proxied. Must not be <code>null</code>.</dd>
</dl>
</li>
</ul>
<a id="catchException(com.googlecode.catchexception.ThrowingCallable,java.lang.Class)">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>catchException</h4>
<pre class="methodSignature">public static&nbsp;void&nbsp;catchException&#8203;(<a href="ThrowingCallable.html" title="interface in com.googlecode.catchexception">ThrowingCallable</a>&nbsp;actor,
                                  <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang" class="externalLink">Class</a>&lt;? extends <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang" class="externalLink">Exception</a>&gt;&nbsp;clazz)</pre>
<div class="block">Use it to catch an exception of a specific type and to get access to the thrown exception (for further
 verifications). In the following example you catch exceptions of type MyException that are thrown by obj.doX():
 <code>catchException(obj, MyException.class).doX(); // catch
 if (caughtException() != null) {
 assert "foobar".equals(caughtException().getMessage()); // further analysis
 }</code> If <code>doX()</code> throws a <code>MyException</code>, then <a href="#caughtException()"><code>caughtException()</code></a> will return the
 caught exception. If <code>doX()</code> does not throw a <code>MyException</code>, then
 <a href="#caughtException()"><code>caughtException()</code></a> will return <code>null</code>. If <code>doX()</code> throws an exception of another
 type, i.e. not a subclass but another class, then this exception is not thrown and <a href="#caughtException()"><code>caughtException()</code></a>
 will return <code>null</code>.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>actor</code> - The instance that shall be proxied. Must not be <code>null</code>.</dd>
<dd><code>clazz</code> - The type of the exception that shall be caught. Must not be <code>null</code>.</dd>
</dl>
</li>
</ul>
<a id="resetCaughtException()">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>resetCaughtException</h4>
<pre class="methodSignature">public static&nbsp;void&nbsp;resetCaughtException()</pre>
<div class="block">Sets the <a href="#caughtException()"><code>caught exception</code></a> to null. This does not affect exceptions saved at threads
 other than the current one. Actually you probably never need to call this method because each method call on a
 proxied object in the current thread resets the caught exception. But if you want to improve test isolation or if
 you want to 'clean up' after testing (to avoid memory leaks), call the method before or after testing.</div>
</li>
</ul>
</li>
</ul>
</section>
</li>
</ul>
</div>
</div>
</main>
<!-- ========= END OF CLASS DATA ========= -->
<footer role="contentinfo">
<nav role="navigation">
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a id="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a id="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../index.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="class-use/CatchException.html">Use</a></li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../index-all.html">Index</a></li>
<li><a href="../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="../../../allclasses.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor.summary">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor.detail">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a id="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
</nav>
<p class="legalCopy"><small>Copyright &#169; 2011&#x2013;2023 <a href="https://github.com/hazendaz/">hazendaz</a>. All rights reserved.</small></p>
</footer>
</body>
</html>